default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DB_USER", "") %>
  password: <%= ENV.fetch("RAIlS_DB_PASSWORD", "") %>
  host:  <%= ENV.fetch("RAILS_DB_HOST", "localhost") %>

development:
  <<: *default
  database: base_app_development

test:
  <<: *default
  database: base_app_test

# 雛形では本番環境の設定は変更していません。適宜変更してください。
production:
  <<: *default
  database: base_app_production
  username: base_app
  password: <%= ENV['BASE_APP_DATABASE_PASSWORD'] %>
